platform :ios, '11.0'

def working_pods
use_frameworks!
    pod 'SnapKit', :inhibit_warnings => true
    pod 'YZNumPad', :git => 'https://github.com/YarZav/YZNumPad.git', :tag => '1.1.0'
    pod 'YZBarChart', :git => 'https://github.com/YarZav/YZBarChart.git', :tag => '1.2.0'
    pod 'YZNotificationView', :git => 'https://github.com/YarZav/YZNotificationView.git', :tag => '1.1.0'
    pod 'YZPinCodeViewController', :git => 'https://github.com/YarZav/YZPinCodeViewController.git', :tag => '1.1.0'

    pod 'EANBarcodeGenerator'
    pod 'Swinject'
end

target 'MoneyKeeper' do
    working_pods
end

